all: keyboard-example read-line-example

tty-raw-mode.o: tty-raw-mode.c
	gcc -c tty-raw-mode.c

read-line.o: read-line.c
	gcc -c read-line.c

keyboard-example: keyboard-example.c tty-raw-mode.o
	gcc -o keyboard-example keyboard-example.c tty-raw-mode.o

read-line-example: read-line-example.c tty-raw-mode.o read-line.o
	gcc -o read-line-example read-line-example.c tty-raw-mode.o read-line.o

clean:
	rm -f keyboard-example read-line-example *.o
